name: CI/CD Pipeline

# Run the workflow when code is pushed to the "main" branch
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from your repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Step 3: Install dependencies (ensure correct directory if needed)
      - name: Install dependencies
        run: npm install
        working-directory: ./   # use ./Node.js-app if your package.json is there

      # Step 4: Run tests (skip if none)
      - name: Run tests
        run: npm test || echo "No tests found"
        working-directory: ./   # same as above

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 1: Checkout code for Docker context
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Login to DockerHub using secrets
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and push Docker image
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .               # change to ./Node.js-app if Dockerfile is there
          push: true
          tags: ninga8141/nodejs-app:latest
