- name: Deploy to EC2
  uses: appleboy/ssh-action@v1.0.3
  with:
    host: 18.183.113.77
    username: ubuntu
    key: ${{ secrets.EC2_KEY }}
    script: |
      # Stop and remove any container using port 4000
      sudo docker ps -q --filter "publish=4000" | xargs -r sudo docker stop
      sudo docker ps -a -q --filter "publish=4000" | xargs -r sudo docker rm
      # Pull latest image and run new container
      sudo docker pull ninga8141/nodejs-app:latest
      sudo docker run -d -p 3000:3000 --name nodejs-container ninga8141/nodejs-app:latest
